apiVersion: run.tanzu.vmware.com/v1alpha1    
kind: TanzuKubernetesCluster                 
metadata:
  name: test-cluster-1        
  namespace: test-namespace
spec:
  distribution:
    version: v1.18  #Resolves to the latest v1.18 image (v1.17.8+vmware.1-tkg.1.5417466)
  topology:
    controlPlane:
      count: 1                                 #number of control plane nodes
      class: guaranteed-medium                 #vmclass for control plane nodes
      storageClass: vsan-default-storage-policy         #storageclass for control plane
    workers:
      count: 2                                 #number of worker nodes
      class: guaranteed-large                 #vmclass for worker nodes
      storageClass: vsan-default-storage-policy         #storageclass for worker nodes   
  settings:
    network:
      cni:
        name: antrea 
      services:
        cidrBlocks: ["198.101.0.0/16"]        #Cannot overlap with Supervisor Cluster
      pods:
        cidrBlocks: ["192.1.0.0/16"]           #Cannot overlap with Supervisor Cluster
    storage:
      classes: ["vsan-default-storage-policy"]              #Named PVC storage classes
      defaultClass: vsan-default-storage-policy   #Default PVC storage class
