apiVersion: run.tanzu.vmware.com/v1alpha1    
kind: TanzuKubernetesCluster                 
metadata:
  name: 1st-dev-cluster      
  namespace: paulos-dev-team
spec:
  distribution:
    version: v1.19  #Resolves to the latest v1.18 image (v1.17.8+vmware.1-tkg.1.5417466)
  topology:
    controlPlane:
      count: 1                                 #number of control plane nodes
      class: guaranteed-medium                 #vmclass for control plane nodes
      storageClass: standard         #storageclass for control plane
    workers:
      count: 1                                 #number of worker nodes
      class: guaranteed-medium                 #vmclass for worker nodes
      storageClass: standard         #storageclass for worker nodes   
  settings:
    network:
      cni:
        name: antrea 
      services:
        cidrBlocks: ["198.101.0.0/16"]        #Cannot overlap with Supervisor Cluster
      pods:
        cidrBlocks: ["192.1.0.0/16"]           #Cannot overlap with Supervisor Cluster
    storage:
      defaultClass: storage   #Default PVC storage class
